const STORE="happy-party-solo-v2";let game;const $=id=>document.getElementById(id);const pick=a=>a[Math.floor(Math.random()*a.length)],clamp=n=>Math.max(0,Math.min(100,n));
document.addEventListener("DOMContentLoaded",()=>{$("consent-checkbox").onchange=e=>$('start-btn').disabled=!e.target.checked;$('start-btn').onclick=start;$('chat-btn').onclick=chat;$('test-btn').onclick=test;$('hospital-btn').onclick=hospital;$('next-btn').onclick=next;$('restart-btn').onclick=start;try{game=JSON.parse(localStorage.getItem(STORE))}catch{}if(game&&game.round<10){$('consent-checkbox').checked=true;$('start-btn').disabled=false;$('start-btn').textContent="繼續上一桌";$('start-btn').onclick=()=>renderRound()}});
function start(){game={round:0,score:0,anxiety:0,heat:0,testkits:1,hospitals:1,playerGender:$('player-gender').value,partnerGender:$('partner-gender').value,log:[]};save();renderRound()}function save(){localStorage.setItem(STORE,JSON.stringify(game))}function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}function partner(){const tags=[pick(TAG_POOL),pick(TAG_POOL),pick(TAG_POOL)],pool=PARTY_PEOPLE.filter(person=>person.gender===(game.partnerGender||'male')),person=pick(pool);return{avatar:person.image,name:person.name,gender:person.gender,flirt:pick(FLIRT_LINES),tags,chat:false,tested:false}}
function renderRound(){if(game.round>=10)return finale();game.partner=partner();$('round-title').textContent=`Round ${game.round+1} / 10`;$('partner-avatar').innerHTML=`<img src="${game.partner.avatar}" alt="${game.partner.gender==='male'?'動漫男性角色':'動漫女性角色'}">`;$('partner-name').textContent=game.partner.name;$('partner-flirt').textContent=`「${game.partner.flirt}」`;renderStats();renderTags();$('chat-btn').disabled=false;$('test-btn').disabled=game.testkits<1;$('hospital-btn').disabled=game.hospitals<1;renderActions();show('round-screen')}
function renderStats(){$('dissatisfaction-value').textContent=`${game.heat}%`;$('dissatisfaction-bar').style.width=`${game.heat}%`;$('anxiety-value').textContent=`${game.anxiety}%`;$('anxiety-bar').style.width=`${game.anxiety}%`;$('score-value').textContent=game.score;$('testkit-value').textContent=`試紙 ${game.testkits} · 醫院 ${game.hospitals}`;$('warning').classList.toggle('hidden',game.anxiety<80)}
function renderTags(){const count=game.anxiety>=80?0:game.anxiety>=50?1:2;$('partner-tags').innerHTML=game.partner.tags.map((t,i)=>i<count?`<span class="tag safe">${t.text}</span>`:`<span class="tag hidden-tag">線索被焦慮遮住</span>`).join('')+(game.partner.chat?'<span class="tag safe">💬 聊天多知道一點</span>':'')+(game.partner.tested?'<span class="tag safe">🧪 試紙很安靜：健康</span>':'')}
function renderActions(){$('action-buttons').innerHTML=Object.entries(ACTIONS).filter(([k])=>k!=="hospital").map(([k,a])=>`<button class="action-btn ${k.includes('raw')?'raw':''}" data-action="${k}"><strong>${a.label}</strong><small>${a.copy}</small></button>`).join('');document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>resolve(b.dataset.action))}
function chat(){game.partner.chat=true;$('chat-btn').disabled=true;renderTags();toast('你多套到一點線索，但外表還是不能當答案。')}
function test(){game.testkits--;game.partner.tested=true;$('test-btn').disabled=true;renderTags();renderStats();toast('試紙很安靜：健康。這版所有角色都是健康者。')}
function hospital(){game.hospitals--;game.anxiety=0;renderStats();$('hospital-btn').disabled=true;toast('醫院檢查：結果健康，焦慮先歸零。');setTimeout(()=>resolve('hospital'),650)}
function resolve(key){const a=ACTIONS[key],p=game.partner;let text=a.copy;if(key==='refuse'){text='你按下換一個。這晚沒互動，但有些直覺本來就值得相信。'}else if(key==='hospital'){text='你去醫院跑了一趟，今晚的配對自然撲空。'}else{text=`你們都選了 ${a.short}，互動成立。${a.risk<20?'有做保護，至少不是全拿運氣猜拳。':'這個單機版裡大家都是健康者，這晚放心留下好回憶。'}`}game.score+=a.score;game.heat=clamp(game.heat+a.heat);game.anxiety=clamp(game.anxiety+a.anxiety);game.log.push({round:game.round+1,name:p.name,avatar:p.avatar,action:a.short,text});game.round++;save();$('summary-title').textContent=`第 ${game.round} 局翻牌`;$('summary-heading').textContent='今晚沒有白來';$('summary-body').textContent=text;$('summary-extra').innerHTML=`<span>對方狀態：健康者</span><span>你的狀態：健康</span><span>生存分：${game.score}</span>`;$('scoreboard').innerHTML=`<div><strong>${a.short}</strong><span>${a.score>=0?'+':''}${a.score} 生存分</span></div>`;$('next-btn').textContent=game.round>=10?'直接開獎去':'下一局，走起';show('summary-screen')}
function next(){game.round>=10?finale():renderRound()}function finale(){const noIntimacy=!game.log.some(x=>!['換一個','去醫院'].includes(x.action));$('finale-heading').textContent=noIntimacy?'你今晚來觀光':'全場真相大白';$('finale-body').textContent=noIntimacy?'整晚都沒親密互動，連頒獎台都摸不到。不過沒事，下一桌再鬧。':'你撐過了這 10 個晚上。大家都是健康者，直覺和好心情今晚都站在你這邊。';$('replay-list').innerHTML=game.log.map(x=>`<article class="replay-item"><img class="replay-avatar" src="${x.avatar}" alt="角色貼圖"><div><strong>Round ${x.round} · ${x.name} · ${x.action}</strong><p>${x.text}</p></div></article>`).join('');localStorage.removeItem(STORE);show('awards-screen')}function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2600)}
